[phases.setup]
aptPkgs = [
    "libgl1",
    "libglib2.0-0",
    "libxcb1",
    "libx11-6",
    "libx11-xcb1",
    "libxcb-render0",
    "libxcb-shape0",
    "libxcb-xfixes0",
    "libxext6",
    "libxrender1",
    "libice6",
    "libsm6",
    "libgl1-mesa-glx"
]
